# Generated by Django 4.2.4 on 2023-08-14 13:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('likes', models.ManyToManyField(related_name='liked_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
