# Generated by Django 4.2.4 on 2023-08-14 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('franchise', '0002_alter_gamecollection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecollection',
            name='likes',
            field=models.ManyToManyField(related_name='liked_collection', to=settings.AUTH_USER_MODEL),
        ),
    ]
