# Generated by Django 4.2.4 on 2023-08-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_studio_games_count'),
        ('franchise', '0004_gamecollection_author_alter_gamecollection_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecollection',
            name='games_list',
            field=models.ManyToManyField(blank=True, related_name='game_collection_list', to='games.game'),
        ),
    ]
