# Generated by Django 4.2.4 on 2023-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_studio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='games_count',
            field=models.IntegerField(default=0, verbose_name='Количество игр'),
        ),
    ]
